name: Tests

on:
  push:
    branches:
      - master
      - test
    paths-ignore:
      - README.md
      - LICENSE
      - CHANGELOG
      - .gitignore

jobs:
  linux:
    name: Linux, Python ${{ matrix.python }}, environment ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {python: "3.9", env: "1"}
          - {python: "3.9", env: "2"}
          - {python: "3.9", env: "3"}
          - {python: "3.9", env: "4"}
    steps:
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          path: |
            ~/.cache

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Run tests
        run: ./ci.sh test "$ENV"
        env:
          ENV: ${{ matrix.env }}
